export const PRODUCT_SORT = 'PRODUCT_SORT';
export const DEFAULT_STATE = 'DEFAULT_STATE';
export const INPUT_SEARCH = 'INPUT_SEARCH';
export const PRODUCT_SORT_PRICE_FROM = 'PRODUCT_SORT_PRICE_FROM';
export const PRODUCT_SORT_PRICE_TO = 'PRODUCT_SORT_PRICE_TO';
export const ADD_TO_BASKET = 'ADD_TO_BASKET';
export const DELETE_FROM_BASKET = 'DELETE_FROM_BASKET';
export const ADD_ORDER = "ADD_ORDER";
