export const INPUT_SEARCH = 'INPUT_SEARCH';
export const ADD_TO_BASKET = 'ADD_TO_BASKET';
export const DELETE_FROM_BASKET = 'DELETE_FROM_BASKET';
export const GET_LIST_PRODUCTS = 'GET_LIST_PRODUCTS';
export const GET_ITEM_PRODUCTS = 'GET_ITEM_PRODUCTS';
